name: Gated
env:
  ICAPDOCKER_USERNAME: icapserviceaccount
  REPOSITORY: glasswallsolutions
  IMAGE: icap-filedrop-ui
  TAG: develop
  IMAGESTORESELECTOR: icapfiledropui

on:
  pull_request:
    branches: [ develop ]

jobs:

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Image
      run: docker build -t ${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ env.TAG }}-${GITHUB_SHA::7} -t ${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ env.TAG }}-latest ./app
       