name: Gated
env:
  IMAGE: icap-filedrop-ui
  
on:
  pull_request:
    branches: [ develop ]

jobs:

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Image
      run: docker build -t ${{ env.IMAGE }} ./app  